/**
 * 职责：创建唯一共享上下文，按固定顺序安装各业务域并返回稳定公开 API。
 * 依赖：unpackBind、跨域 ports 与 register*（再导出 runtime/install*）。
 * 副作用：安装器会注册 computed、监听、provide 与画布生命周期。
 *
 * 注意：必须只创建一次（由 registerSupport WeakMap 保证），避免重复 onMounted/provide。
 */
import type { CanvasBindings } from './types'
import type { CanvasCorePorts } from './corePorts'
import { unpackBind } from './bindContext'
import type { CoreRuntimeContext } from './runtime/context'
import { registerDerivedState } from './registerDerivedState'
import { registerMediaGeneration } from './registerMediaGeneration'
import { registerPromptGeneration } from './registerPromptGeneration'
import { registerDialogue } from './registerDialogue'
import { registerImageMarking } from './registerImageMarking'
import { registerPersistence } from './registerPersistence'
import { registerConnections } from './registerConnections'
import { registerAssetInsertion } from './registerAssetInsertion'
import { registerHistoryClipboard } from './registerHistoryClipboard'
import { registerGroups } from './registerGroups'
import { registerGraphLifecycle } from './registerGraphLifecycle'
import { installPersistenceState } from './runtime/installPersistence'
import { installHistoryState } from './runtime/installHistoryClipboard'

export function createCoreRuntime(bind: CanvasBindings, ports: CanvasCorePorts) {
  const ctx = { bind, ports } as CoreRuntimeContext
  Object.assign(ctx, unpackBind(bind))

  // 保存队列与历史栈状态先初始化，实现仍由各自业务域安装。
  installPersistenceState(ctx)
  installHistoryState(ctx)
  registerDerivedState(ctx)
  registerMediaGeneration(ctx)
  registerPromptGeneration(ctx)
  registerDialogue(ctx)
  registerImageMarking(ctx)
  registerPersistence(ctx)
  registerConnections(ctx)
  registerAssetInsertion(ctx)
  registerHistoryClipboard(ctx)
  registerGroups(ctx)
  registerGraphLifecycle(ctx)

  return {
    activeGroupSelection: ctx.activeGroupSelection,
    overlayGroupSelection: ctx.overlayGroupSelection,
    showGroupOverlay: ctx.showGroupOverlay,
    addElementGroupFromRecord: ctx.addElementGroupFromRecord,
    addFromMenu: ctx.addFromMenu,
    appendImageDialogueDigitalHumanRef: ctx.appendImageDialogueDigitalHumanRef,
    addImageDialogueSourceRef: ctx.addImageDialogueSourceRef,
    addImageFromAsset: ctx.addImageFromAsset,
    addVideoFromAsset: ctx.addVideoFromAsset,
    batchInsertAssetsFromLibrary: ctx.batchInsertAssetsFromLibrary,
    addImageFromFile: ctx.addImageFromFile,
    addImagesFromFiles: ctx.addImagesFromFiles,
    createNodeFromChatTask: ctx.createNodeFromChatTask,
    updateChatTaskNodeTitleFromPayload: ctx.updateChatTaskNodeTitleFromPayload,
    addNode: ctx.addNode,
    addPromptImageSourceRef: ctx.addPromptImageSourceRef,
    altVoiceTimer: ctx.altVoiceTimer,
    applyIncomingImageSource: ctx.applyIncomingImageSource,
    applyZoomAfterChange: ctx.applyZoomAfterChange,
    bindKeyboard: ctx.bindKeyboard,
    bindLongPressPan: ctx.bindLongPressPan,
    bindScrollerScrollListener: ctx.bindScrollerScrollListener,
    bumpToolbarRevision: ctx.bumpToolbarRevision,
    canShowImageToolbar: ctx.canShowImageToolbar,
    canShowVideoToolbar: ctx.canShowVideoToolbar,
    canSubmitTextPrompt: ctx.canSubmitTextPrompt,
    cancelCurrentOperation: ctx.cancelCurrentOperation,
    canvasBgThemeLabel: ctx.canvasBgThemeLabel,
    clearEdgeSelection: ctx.clearEdgeSelection,
    clearImageDialoguePreview: ctx.clearImageDialoguePreview,
    closeAddMenu: ctx.closeAddMenu,
    closeConnectMenu: ctx.closeConnectMenu,
    closeImageContextMenu: ctx.closeImageContextMenu,
    closeHistoryPanel: ctx.closeHistoryPanel,
    closeImageCrop: ctx.closeImageCrop,
    closeImageErase: ctx.closeImageErase,
    closeImageInpaint: ctx.closeImageInpaint,
    closeImageExpand: ctx.closeImageExpand,
    closeImageEditText: ctx.closeImageEditText,
    closeImageGridSplit: ctx.closeImageGridSplit,
    onImageEraseComplete: ctx.onImageEraseComplete,
    onImageInpaintComplete: ctx.onImageInpaintComplete,
    onImageExpandComplete: ctx.onImageExpandComplete,
    onImageEditTextApply: ctx.onImageEditTextApply,
    onImageGridSplitComplete: ctx.onImageGridSplitComplete,
    closeImageGenPromptBar: ctx.closeImageGenPromptBar,
    closeImagePreview: ctx.closeImagePreview,
    closeImageToolbarMore: ctx.closeImageToolbarMore,
    closeProjectMenu: ctx.closeProjectMenu,
    closeProjectBrowser: ctx.closeProjectBrowser,
    openProjectBrowser: ctx.openProjectBrowser,
    closeShortcutsPanel: ctx.closeShortcutsPanel,
    closeTextExpand: ctx.closeTextExpand,
    closeUserMenu: ctx.closeUserMenu,
    closeVideoGenPromptBar: ctx.closeVideoGenPromptBar,
    closeVideoSubPanels: ctx.closeVideoSubPanels,
    closeZoomMenu: ctx.closeZoomMenu,
    copySelectedNode: ctx.copySelectedNode,
    copySelectedNodes: ctx.copySelectedNodes,
    currentProjectName: ctx.currentProjectName,
    detachImageSourceFromDownstream: ctx.detachImageSourceFromDownstream,
    dismissOneCanvasLayer: ctx.dismissOneCanvasLayer,
    downloadSelectedTextNode: ctx.downloadSelectedTextNode,
    duplicateSelectedNodes: ctx.duplicateSelectedNodes,
    endSpacePan: ctx.endSpacePan,
    elementMarks: ctx.elementMarks,
    imageMarkAnalyzingActive: ctx.imageMarkAnalyzingActive,
    mentionInsertSerial: ctx.mentionInsertSerial,
    mentionInsertToken: ctx.mentionInsertToken,
    enterElementSelectMode: ctx.enterElementSelectMode,
    exitElementSelectMode: ctx.exitElementSelectMode,
    exitVideoGenCanvasPickMode: ctx.exitVideoGenCanvasPickMode,
    exitImageDialogueCanvasPickMode: ctx.exitImageDialogueCanvasPickMode,
    toggleVideoGenCanvasPickMode: ctx.toggleVideoGenCanvasPickMode,
    toggleImageDialogueCanvasPickMode: ctx.toggleImageDialogueCanvasPickMode,
    toggleImageDialogueMarkMode: ctx.toggleImageDialogueMarkMode,
    updateImageMarkLabel: ctx.updateImageMarkLabel,
    removeElementMark: ctx.removeElementMark,
    clearElementMarks: ctx.clearElementMarks,
    resolveElementMarkPreviewUrl: ctx.resolveElementMarkPreviewUrl,
    filterUploadFiles: ctx.filterUploadFiles,
    finishConnectSpawn: ctx.finishConnectSpawn,
    generateImageFromPrompt: ctx.generateImageFromPrompt,
    handleImageDialogueSubmit: ctx.handleImageDialogueSubmit,
    handleVideoDialogueSubmit: ctx.handleVideoDialogueSubmit,
    handleVideoGenPromptSubmit: ctx.handleVideoGenPromptSubmit,
    getActiveSelectedNodeIds: ctx.getActiveSelectedNodeIds,
    getEdgeReleasePoint: ctx.getEdgeReleasePoint,
    getGraphCenter: ctx.getGraphCenter,
    getGraphSelectedNodeIds: ctx.getGraphSelectedNodeIds,
    getHistoryMeta: ctx.getHistoryMeta,
    getHorizontalUploadSpawnPoint: ctx.getHorizontalUploadSpawnPoint,
    getMultiUploadSpawnPoint: ctx.getMultiUploadSpawnPoint,
    getSelectedNode: ctx.getSelectedNode,
    getSelectedNodeData: ctx.getSelectedNodeData,
    getVideoGenSourceLimit: ctx.getVideoGenSourceLimit,
    goUserCenter: ctx.goUserCenter,
    handleApplyImageGenTask: ctx.handleApplyImageGenTask,
    handleBlankDblClick: ctx.handleBlankDblClick,
    handleEdgeClick: ctx.handleEdgeClick,
    handleEdgeConnected: ctx.handleEdgeConnected,
    handleExportCanvas: ctx.handleExportCanvas,
    handleGroupAddToToolbox: ctx.handleGroupAddToToolbox,
    handleGroupBatchDownload: ctx.handleGroupBatchDownload,
    handleGroupExecute: ctx.handleGroupExecute,
    handleGroupLayout: ctx.handleGroupLayout,
    handleGroupSaveToSkill: ctx.handleGroupSaveToSkill,
    handleGroupToStoryboard: ctx.handleGroupToStoryboard,
    handleSubmitSaveSkill: ctx.handleSubmitSaveSkill,
    closeSaveSkillPopover: ctx.closeSaveSkillPopover,
    closeImageToolbarCustomize: ctx.closeImageToolbarCustomize,
    saveImageToolbarCustomize: ctx.saveImageToolbarCustomize,
    resetImageToolbarCustomize: ctx.resetImageToolbarCustomize,
    listSavedCanvasSkills: ctx.listSavedCanvasSkills,
    handleImageNodeDblClick: ctx.handleImageNodeDblClick,
    handleVideoNodeDblClick: ctx.handleVideoNodeDblClick,
    handleLogout: ctx.handleLogout,
    handleMergeStoryboardGroup: ctx.handleMergeStoryboardGroup,
    handleMultiSelectGroup: ctx.handleMultiSelectGroup,
    handleMultiSelectLayout: ctx.handleMultiSelectLayout,
    handleMultiSelectSaveToAssets: ctx.handleMultiSelectSaveToAssets,
    handleMultiSelectBatchDownload: ctx.handleMultiSelectBatchDownload,
    handleNodeClick: ctx.handleNodeClick,
    handleNodeDataChange: ctx.handleNodeDataChange,
    handleNodeEdgeLinked: ctx.handleNodeEdgeLinked,
    handleOpenVideoGenPromptBar: ctx.handleOpenVideoGenPromptBar,
    handleRedo: ctx.handleRedo,
    handleSaveCanvas: ctx.handleSaveCanvas,
    hasUnsavedChanges: ctx.hasUnsavedChanges,
    saveCanvasAndWait: ctx.saveCanvasAndWait,
    setCanvasDescription: ctx.setCanvasDescription,
    loadProjectCanvas: ctx.loadProjectCanvas,
    loadProjectCanvasFromVersion: ctx.loadProjectCanvasFromVersion,
    beginProjectCanvasSwitch: ctx.beginProjectCanvasSwitch,
    getCanvasBoundProjectId: ctx.getCanvasBoundProjectId,
    handleTextPickerAction: ctx.handleTextPickerAction,
    handleTidyCanvas: ctx.handleTidyCanvas,
    handleUndo: ctx.handleUndo,
    handleUngroup: ctx.handleUngroup,
    handleUserMenuAction: ctx.handleUserMenuAction,
    hasCanvasFileDrag: ctx.hasCanvasFileDrag,
    imageCropSource: ctx.imageCropSource,
    imageEraseSource: ctx.imageEraseSource,
    imageInpaintSource: ctx.imageInpaintSource,
    imageExpandSource: ctx.imageExpandSource,
    imageGridSplitSource: ctx.imageGridSplitSource,
    imageDialoguePreviewUrl: ctx.imageDialoguePreviewUrl,
    imageDialoguePreviews: ctx.imageDialoguePreviews,
    imageDialogueWorkflowDisabled: ctx.imageDialogueWorkflowDisabled,
    imageDialogueHideWorkflowAndMark: ctx.imageDialogueHideWorkflowAndMark,
    isImageUploadFile: ctx.isImageUploadFile,
    isImg2PromptTask: ctx.isImg2PromptTask,
    isText2VideoTask: ctx.isText2VideoTask,
    isText2ImageTask: ctx.isText2ImageTask,
    promptSubmitLabel: ctx.promptSubmitLabel,
    isLightNodeToolbar: ctx.isLightNodeToolbar,
    isVideoUploadFile: ctx.isVideoUploadFile,
    linkImageNodeToImageDialogue: ctx.linkImageNodeToImageDialogue,
    linkImageNodeToVideoGen: ctx.linkImageNodeToVideoGen,
    linkImageSourceFromEdge: ctx.linkImageSourceFromEdge,
    loadImageGenPromptFields: ctx.loadImageGenPromptFields,
    loadImageDialogueFields: ctx.loadImageDialogueFields,
    loadVideoDialogueFields: ctx.loadVideoDialogueFields,
    loadPromptBarContext: ctx.loadPromptBarContext,
    loadVideoGenPromptFields: ctx.loadVideoGenPromptFields,
    moveNodeLayer: ctx.moveNodeLayer,
    onCanvasDragEnter: ctx.onCanvasDragEnter,
    onCanvasDragLeave: ctx.onCanvasDragLeave,
    onCanvasDragOver: ctx.onCanvasDragOver,
    onCanvasFileDrop: ctx.onCanvasFileDrop,
    onConnectMenuItem: ctx.onConnectMenuItem,
    onFileSelected: ctx.onFileSelected,
    onGoHome: ctx.onGoHome,
    onGroupOverlayDragStart: ctx.onGroupOverlayDragStart,
    onGroupOverlayResizeStart: ctx.onGroupOverlayResizeStart,
    onGroupOverlaySelectGroup: ctx.onGroupOverlaySelectGroup,
    onGroupOverlayTitleChange: ctx.onGroupOverlayTitleChange,
    onImageCropComplete: ctx.onImageCropComplete,
    onImageResizePointerDown: ctx.onImageResizePointerDown,
    onImageDialogueAddCanvasNode: ctx.onImageDialogueAddCanvasNode,
    onImageDialogueAddDigitalHumanRef: ctx.onImageDialogueAddDigitalHumanRef,
    onImageDialogueUploadFiles: ctx.onImageDialogueUploadFiles,
    onImageContextMenuAction: ctx.onImageContextMenuAction,
    onImageToolbarAction: ctx.onImageToolbarAction,
    imageContextMenuLocked: ctx.imageContextMenuLocked,
    onVideoToolbarAction: ctx.onVideoToolbarAction,
    onLoadProjects: ctx.onLoadProjects,
    onMenuItem: ctx.onMenuItem,
    onPromptAddCanvasNode: ctx.onPromptAddCanvasNode,
    onPromptUploadFiles: ctx.onPromptUploadFiles,
    onRemoveImageGenSourceRef: ctx.onRemoveImageGenSourceRef,
    onRemoveVideoSourceRef: ctx.onRemoveVideoSourceRef,
    onScrollerScroll: ctx.onScrollerScroll,
    onTextExpandInput: ctx.onTextExpandInput,
    onTextFormatAction: ctx.onTextFormatAction,
    onVideoGenAddCanvasNode: ctx.onVideoGenAddCanvasNode,
    onVideoGenQuickAction: ctx.onVideoGenQuickAction,
    onVideoGenUploadFiles: ctx.onVideoGenUploadFiles,
    onVideoHdStart: ctx.onVideoHdStart,
    onZoomMenuAction: ctx.onZoomMenuAction,
    openAddMenuAtGraphPoint: ctx.openAddMenuAtGraphPoint,
    openAssetsPanel: ctx.openAssetsPanel,
    openComboModal: ctx.openComboModal,
    openConnectMenu: ctx.openConnectMenu,
    openConnectMenuByNodeId: ctx.openConnectMenuByNodeId,
    openFileUploadPicker: ctx.openFileUploadPicker,
    openImageCrop: ctx.openImageCrop,
    openImageErase: ctx.openImageErase,
    openImageInpaint: ctx.openImageInpaint,
    openImageExpand: ctx.openImageExpand,
    openImageDialogue: ctx.openImageDialogue,
    openVideoDialogue: ctx.openVideoDialogue,
    openImageGenPromptBar: ctx.openImageGenPromptBar,
    openImagePreview: ctx.openImagePreview,
    openImageToolbarMore: ctx.openImageToolbarMore,
    openNewProject: ctx.openNewProject,
    openTextExpand: ctx.openTextExpand,
    openVideoGenPromptBar: ctx.openVideoGenPromptBar,
    pasteNode: ctx.pasteNode,
    pasteNodePayload: ctx.pasteNodePayload,
    persistImageGenPrompt: ctx.persistImageGenPrompt,
    persistImageDialogueFields: ctx.persistImageDialogueFields,
    persistVideoDialogueFields: ctx.persistVideoDialogueFields,
    persistPromptBarDraft: ctx.persistPromptBarDraft,
    persistTextExpandContent: ctx.persistTextExpandContent,
    persistVideoGenPrompt: ctx.persistVideoGenPrompt,
    plainTextToEditorHtml: ctx.plainTextToEditorHtml,
    recenterToNodes: ctx.recenterToNodes,
    refreshPromptSourcePreviews: ctx.refreshPromptSourcePreviews,
    removeConnectPreviewEdge: ctx.removeConnectPreviewEdge,
    removeNodeById: ctx.removeNodeById,
    removePromptImageSource: ctx.removePromptImageSource,
    removeSelectedEdge: ctx.removeSelectedEdge,
    removeSelectedNodes: ctx.removeSelectedNodes,
    requestCanvasUpload: ctx.requestCanvasUpload,
    resetCanvasInteractionState: ctx.resetCanvasInteractionState,
    resetImageCrop: ctx.resetImageCrop,
    resetImageExpand: ctx.resetImageExpand,
    resetImageEditText: ctx.resetImageEditText,
    resetImageGridSplit: ctx.resetImageGridSplit,
    resetImageDialogue: ctx.resetImageDialogue,
    resetImageToolbarMore: ctx.resetImageToolbarMore,
    resetVideoDialogue: ctx.resetVideoDialogue,
    resetVideoFramesPanel: ctx.resetVideoFramesPanel,
    resetVideoHdPanel: ctx.resetVideoHdPanel,
    returnFromElementSelect: ctx.returnFromElementSelect,
    scheduleHistoryPush: ctx.scheduleHistoryPush,
    seedImageDialogueRefs: ctx.seedImageDialogueRefs,
    seedPromptImageRefs: ctx.seedPromptImageRefs,
    selectGraphNodes: ctx.selectGraphNodes,
    selectProject: ctx.selectProject,
    setRubberbandEnabled: ctx.setRubberbandEnabled,
    setupMinimap: ctx.setupMinimap,
    showGroupToolbar: ctx.showGroupToolbar,
    showSaveSkillPopover: ctx.showSaveSkillPopover,
    saveSkillPopoverPos: ctx.saveSkillPopoverPos,
    saveSkillItems: ctx.saveSkillItems,
    saveSkillSubmitting: ctx.saveSkillSubmitting,
    showImageCreativeToolbar: ctx.showImageCreativeToolbar,
    showElementSelectBar: ctx.showElementSelectBar,
    imageMarkHintVisible: ctx.imageMarkHintVisible,
    imageMarkHints: ctx.imageMarkHints,
    showImageGenPromptBar: ctx.showImageGenPromptBar,
    showImageToolbarCustomize: ctx.showImageToolbarCustomize,
    imageToolbarCustomizeSettings: ctx.imageToolbarCustomizeSettings,
    showMultiSelectToolbar: ctx.showMultiSelectToolbar,
    showNodeToolbar: ctx.showNodeToolbar,
    showPromptBar: ctx.showPromptBar,
    showTextFormatToolbar: ctx.showTextFormatToolbar,
    showToolbarFeatureButtons: ctx.showToolbarFeatureButtons,
    showVideoGenPromptBar: ctx.showVideoGenPromptBar,
    showVideoDialoguePanel: ctx.showVideoDialoguePanel,
    spawnMediaFilesAtPoint: ctx.spawnMediaFilesAtPoint,
    submitTextPrompt: ctx.submitTextPrompt,
    syncConnectPreviewEdgeTarget: ctx.syncConnectPreviewEdgeTarget,
    syncGroupedNodeMove: ctx.syncGroupedNodeMove,
    syncHistoryState: ctx.syncHistoryState,
    syncNodeCount: ctx.syncNodeCount,
    syncNodeSelectionHighlight: ctx.syncNodeSelectionHighlight,
    syncSelectionFromGraph: ctx.syncSelectionFromGraph,
    syncViewportNodeVisibility: ctx.syncViewportNodeVisibility,
    syncZoom: ctx.syncZoom,
    teardownMinimap: ctx.teardownMinimap,
    toggleAddMenu: ctx.toggleAddMenu,
    toggleAssetsPanel: ctx.toggleAssetsPanel,
    toggleAssetCenterPanel: ctx.toggleAssetCenterPanel,
    loadAssetCenterItems: ctx.loadAssetCenterItems,
    closeAssetCenterPanel: ctx.closeAssetCenterPanel,
    toggleCanvasBgTheme: ctx.toggleCanvasBgTheme,
    toggleGrid: ctx.toggleGrid,
    toggleHistoryPanel: ctx.toggleHistoryPanel,
    toggleImageAddToDialogMenu: ctx.toggleImageAddToDialogMenu,
    addVideoToDialog: ctx.addVideoToDialog,
    toggleImageDialogue: ctx.toggleImageDialogue,
    toggleImageHdMenu: ctx.toggleImageHdMenu,
    toggleImageToolbarMoreMenu: ctx.toggleImageToolbarMoreMenu,
    toggleMinimap: ctx.toggleMinimap,
    togglePanMode: ctx.togglePanMode,
    toggleProjectMenu: ctx.toggleProjectMenu,
    toggleShortcutsPanel: ctx.toggleShortcutsPanel,
    toggleUserMenu: ctx.toggleUserMenu,
    toggleVideoDialogue: ctx.toggleVideoDialogue,
    toggleVideoFramesPanel: ctx.toggleVideoFramesPanel,
    toggleVideoHdPanel: ctx.toggleVideoHdPanel,
    toggleZoomMenu: ctx.toggleZoomMenu,
    triggerCanvasUploadShortcut: ctx.triggerCanvasUploadShortcut,
    triggerFileInputClick: ctx.triggerFileInputClick,
    unbindKeyboard: ctx.unbindKeyboard,
    unbindLongPressPan: ctx.unbindLongPressPan,
    unbindScrollerScrollListener: ctx.unbindScrollerScrollListener,
    updateAddMenuPosition: ctx.updateAddMenuPosition,
    updateConnectMenuPosition: ctx.updateConnectMenuPosition,
    updateGroupToolbarPosition: ctx.updateGroupToolbarPosition,
    updateImageGenPromptBarPosition: ctx.updateImageGenPromptBarPosition,
    updateMultiSelectToolbarPosition: ctx.updateMultiSelectToolbarPosition,
    updateNodeToolbar: ctx.updateNodeToolbar,
    updatePromptBarPosition: ctx.updatePromptBarPosition,
    updateTextFormatToolbarPosition: ctx.updateTextFormatToolbarPosition,
    updateVideoGenPromptBarPosition: ctx.updateVideoGenPromptBarPosition,
    edgeDeleteBtnPos: ctx.edgeDeleteBtnPos,
    showEdgeDeleteButton: ctx.showEdgeDeleteButton,
    handleEdgeDeletePointerEnter: ctx.handleEdgeDeletePointerEnter,
    handleEdgeDeletePointerLeave: ctx.handleEdgeDeletePointerLeave,
    removeHoveredEdge: ctx.removeHoveredEdge,
    uploadFileToCanvasNode: ctx.uploadFileToCanvasNode,
    imageGenSourceRefs: ctx.imageGenSourceRefs,
    videoGenSourceRefs: ctx.videoGenSourceRefs,
    videoGenSavedSettings: ctx.videoGenSavedSettings,
    videoDialogueSourceRefs: ctx.videoDialogueSourceRefs,
    videoGenAspectRatio: ctx.videoGenAspectRatio,
    onVideoGenAspectRatioChange: ctx.onVideoGenAspectRatioChange,
    waitForNodeUploadDone: ctx.waitForNodeUploadDone,
    zoomFitToScreen: ctx.zoomFitToScreen,
    zoomIn: ctx.zoomIn,
    zoomOut: ctx.zoomOut,
    zoomPercent: ctx.zoomPercent,
    zoomToScale: ctx.zoomToScale,
  }
}
