/**
 * 安装器写入、且尚未进入领域接口的动态方法。
 * 使用方法语法（对参数双变）以便赋值与调用都能通过。
 * 未声明字段不再经 any 索引变成 any，拼写错误会在 unknown 索引上报错。
 */

/** 动态方法返回值尚未按域收紧；与 unknown 参数配对，避免 any 索引污染整个 ctx。 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- 说明：槽位返回值短期保持宽松
type CoreRuntimeSlotReturn = any // unknown-arg slots

export interface CoreRuntimeInstallSlots {

  addElementGroupFromRecord(...args: unknown[]): CoreRuntimeSlotReturn
  addFromMenu(...args: unknown[]): CoreRuntimeSlotReturn
  addImageDialogueSourceRef(...args: unknown[]): CoreRuntimeSlotReturn
  addImageFromAsset(...args: unknown[]): CoreRuntimeSlotReturn
  addImageToMyModels(...args: unknown[]): CoreRuntimeSlotReturn
  addImagesFromFiles(...args: unknown[]): CoreRuntimeSlotReturn
  addNode(...args: unknown[]): CoreRuntimeSlotReturn
  addPromptImageSourceRef(...args: unknown[]): CoreRuntimeSlotReturn
  addVideoFromAsset(...args: unknown[]): CoreRuntimeSlotReturn
  addVideoToDialog(...args: unknown[]): CoreRuntimeSlotReturn
  appendImageDialogueDigitalHumanRef(...args: unknown[]): CoreRuntimeSlotReturn
  applyImageDialogueProvenance(...args: unknown[]): CoreRuntimeSlotReturn
  applyIncomingImageSource(...args: unknown[]): CoreRuntimeSlotReturn
  applyProjectCanvasPayload(...args: unknown[]): CoreRuntimeSlotReturn
  applyToolbarImageGenerationSnapshot(...args: unknown[]): CoreRuntimeSlotReturn
  applyVideoGenerationProvenance(...args: unknown[]): CoreRuntimeSlotReturn
  applyZoomAfterChange(...args: unknown[]): CoreRuntimeSlotReturn
  batchInsertAssetsFromLibrary(...args: unknown[]): CoreRuntimeSlotReturn
  bindGraphDropListeners(...args: unknown[]): CoreRuntimeSlotReturn
  bindKeyboard(...args: unknown[]): CoreRuntimeSlotReturn
  bindLongPressPan(...args: unknown[]): CoreRuntimeSlotReturn
  bindScrollerScrollListener(...args: unknown[]): CoreRuntimeSlotReturn
  buildVideoDialogueSettingsFromPayload(...args: unknown[]): CoreRuntimeSlotReturn
  bumpToolbarRevision(...args: unknown[]): CoreRuntimeSlotReturn
  canAutoOpenImageDialogue(...args: unknown[]): CoreRuntimeSlotReturn
  canAutoOpenVideoDialogue(...args: unknown[]): CoreRuntimeSlotReturn
  canNodeHostImageDialogue(...args: unknown[]): CoreRuntimeSlotReturn
  canOpenImageContextMenu(...args: unknown[]): CoreRuntimeSlotReturn
  canOpenMediaContextMenu(...args: unknown[]): CoreRuntimeSlotReturn
  canOpenVideoContextMenu(...args: unknown[]): CoreRuntimeSlotReturn
  canShowImageToolbar(...args: unknown[]): CoreRuntimeSlotReturn
  canShowVideoToolbar(...args: unknown[]): CoreRuntimeSlotReturn
  cancelBlankPanGesture(...args: unknown[]): CoreRuntimeSlotReturn
  cancelCurrentOperation(...args: unknown[]): CoreRuntimeSlotReturn
  cancelVideoToolbarDefer(...args: unknown[]): CoreRuntimeSlotReturn
  clearCanvasTextSelection(...args: unknown[]): CoreRuntimeSlotReturn
  clearEdgeHoverState(...args: unknown[]): CoreRuntimeSlotReturn
  clearEdgeSelection(...args: unknown[]): CoreRuntimeSlotReturn
  clearImageDialoguePreview(...args: unknown[]): CoreRuntimeSlotReturn
  clearImageElementMarkSelection(...args: unknown[]): CoreRuntimeSlotReturn
  closeAddMenu(...args: unknown[]): CoreRuntimeSlotReturn
  closeAssetCenterPanel(...args: unknown[]): CoreRuntimeSlotReturn
  closeConnectMenu(...args: unknown[]): CoreRuntimeSlotReturn
  closeHistoryPanel(...args: unknown[]): CoreRuntimeSlotReturn
  closeImageContextMenu(...args: unknown[]): CoreRuntimeSlotReturn
  closeImageCrop(...args: unknown[]): CoreRuntimeSlotReturn
  closeImageGenPromptBar(...args: unknown[]): CoreRuntimeSlotReturn
  closeImagePreview(...args: unknown[]): CoreRuntimeSlotReturn
  closeImageToolbarMore(...args: unknown[]): CoreRuntimeSlotReturn
  closeNodeDialoguePanels(...args: unknown[]): CoreRuntimeSlotReturn
  closeProjectMenu(...args: unknown[]): CoreRuntimeSlotReturn
  closeSaveSkillPopover(...args: unknown[]): CoreRuntimeSlotReturn
  closeShortcutsPanel(...args: unknown[]): CoreRuntimeSlotReturn
  closeTextExpand(...args: unknown[]): CoreRuntimeSlotReturn
  closeTextPromptBar(...args: unknown[]): CoreRuntimeSlotReturn
  closeUserMenu(...args: unknown[]): CoreRuntimeSlotReturn
  closeVideoGenPromptBar(...args: unknown[]): CoreRuntimeSlotReturn
  closeVideoSubPanels(...args: unknown[]): CoreRuntimeSlotReturn
  closeZoomMenu(...args: unknown[]): CoreRuntimeSlotReturn
  computeImageMarkHintPositions(...args: unknown[]): CoreRuntimeSlotReturn
  copySelectedNode(...args: unknown[]): CoreRuntimeSlotReturn
  copySelectedNodes(...args: unknown[]): CoreRuntimeSlotReturn
  countSkillFiles(...args: unknown[]): CoreRuntimeSlotReturn
  createNodeFromChatTask(...args: unknown[]): CoreRuntimeSlotReturn
  createPastedCanvasNodeId(...args: unknown[]): CoreRuntimeSlotReturn
  dataUrlToFile(...args: unknown[]): CoreRuntimeSlotReturn
  detachImageSourceFromDownstream(...args: unknown[]): CoreRuntimeSlotReturn
  dismissCanvasNodeChromeForShellPanel(...args: unknown[]): CoreRuntimeSlotReturn
  dismissOneCanvasLayer(...args: unknown[]): CoreRuntimeSlotReturn
  dismissTextPickerPanels(...args: unknown[]): CoreRuntimeSlotReturn
  distributeMultiImageGenerationResults(...args: unknown[]): CoreRuntimeSlotReturn
  downloadSelectedTextNode(...args: unknown[]): CoreRuntimeSlotReturn
  drainPendingSaveJobs(...args: unknown[]): CoreRuntimeSlotReturn
  duplicateSelectedNodes(...args: unknown[]): CoreRuntimeSlotReturn
  endSpacePan(...args: unknown[]): CoreRuntimeSlotReturn
  enqueuePendingSaveJob(...args: unknown[]): CoreRuntimeSlotReturn
  ensureCanvasReadyForAutoSave(...args: unknown[]): CoreRuntimeSlotReturn
  ensureGenerationResultLoadingNodes(...args: unknown[]): CoreRuntimeSlotReturn
  ensureSelectedImageNodeDimensions(...args: unknown[]): CoreRuntimeSlotReturn
  enterElementSelectMode(...args: unknown[]): CoreRuntimeSlotReturn
  enterImageDialogueCanvasPickMode(...args: unknown[]): CoreRuntimeSlotReturn
  enterVideoGenCanvasPickMode(...args: unknown[]): CoreRuntimeSlotReturn
  executeGroupAiImageTask(...args: unknown[]): CoreRuntimeSlotReturn
  executeGroupAiTask(...args: unknown[]): CoreRuntimeSlotReturn
  executeGroupAiTextCopyTask(...args: unknown[]): CoreRuntimeSlotReturn
  executeGroupAiTextImg2PromptTask(...args: unknown[]): CoreRuntimeSlotReturn
  executeGroupAiVideoTask(...args: unknown[]): CoreRuntimeSlotReturn
  exitElementSelectMode(...args: unknown[]): CoreRuntimeSlotReturn
  exitImageDialogueCanvasPickMode(...args: unknown[]): CoreRuntimeSlotReturn
  exitVideoGenCanvasPickMode(...args: unknown[]): CoreRuntimeSlotReturn
  extractLatestRevision(...args: unknown[]): CoreRuntimeSlotReturn
  filterUploadFiles(...args: unknown[]): CoreRuntimeSlotReturn
  findCanvasProject(...args: unknown[]): CoreRuntimeSlotReturn
  findElementMarkById(...args: unknown[]): CoreRuntimeSlotReturn
  findGroupBlankAreaAtClientPoint(...args: unknown[]): CoreRuntimeSlotReturn
  findGroupIdAtContainerPoint(...args: unknown[]): CoreRuntimeSlotReturn
  findMediaNodeAtClientPoint(...args: unknown[]): CoreRuntimeSlotReturn
  findNodeAtGraphLocalPoint(...args: unknown[]): CoreRuntimeSlotReturn
  finishConnectSpawn(...args: unknown[]): CoreRuntimeSlotReturn
  generateImageFromPrompt(...args: unknown[]): CoreRuntimeSlotReturn
  getActiveImageDialogueTargetNodeId(...args: unknown[]): CoreRuntimeSlotReturn
  getActiveVideoTargetNodeId(...args: unknown[]): CoreRuntimeSlotReturn
  getEdgeReleasePoint(...args: unknown[]): CoreRuntimeSlotReturn
  getElementMarkOwnerNodeId(...args: unknown[]): CoreRuntimeSlotReturn
  getGraphCenter(...args: unknown[]): CoreRuntimeSlotReturn
  getGraphSelectedNodeIds(...args: unknown[]): CoreRuntimeSlotReturn
  getHistoryMeta(...args: unknown[]): CoreRuntimeSlotReturn
  getHorizontalUploadSpawnPoint(...args: unknown[]): CoreRuntimeSlotReturn
  getMultiUploadSpawnPoint(...args: unknown[]): CoreRuntimeSlotReturn
  getSelectedNode(...args: unknown[]): CoreRuntimeSlotReturn
  getTextNodePlainContent(...args: unknown[]): CoreRuntimeSlotReturn
  getVideoGenSourceLimit(...args: unknown[]): CoreRuntimeSlotReturn
  goUserCenter(...args: unknown[]): CoreRuntimeSlotReturn
  handleApplyImageGenTask(...args: unknown[]): CoreRuntimeSlotReturn
  handleBlankDblClick(...args: unknown[]): CoreRuntimeSlotReturn
  handleCanvasAssetDrop(...args: unknown[]): CoreRuntimeSlotReturn
  handleEdgeClick(...args: unknown[]): CoreRuntimeSlotReturn
  handleEdgeConnected(...args: unknown[]): CoreRuntimeSlotReturn
  handleEdgeDeletePointerEnter(...args: unknown[]): CoreRuntimeSlotReturn
  handleEdgeDeletePointerLeave(...args: unknown[]): CoreRuntimeSlotReturn
  handleEdgeMouseEnter(...args: unknown[]): CoreRuntimeSlotReturn
  handleEdgeMouseLeave(...args: unknown[]): CoreRuntimeSlotReturn
  handleExportCanvas(...args: unknown[]): CoreRuntimeSlotReturn
  handleGroupAddToToolbox(...args: unknown[]): CoreRuntimeSlotReturn
  handleGroupBatchDownload(...args: unknown[]): CoreRuntimeSlotReturn
  handleGroupBlankMouseDown(...args: unknown[]): CoreRuntimeSlotReturn
  handleGroupExecute(...args: unknown[]): CoreRuntimeSlotReturn
  handleGroupLayout(...args: unknown[]): CoreRuntimeSlotReturn
  handleGroupSaveToSkill(...args: unknown[]): CoreRuntimeSlotReturn
  handleGroupToStoryboard(...args: unknown[]): CoreRuntimeSlotReturn
  handleGroupedNodeMoved(...args: unknown[]): CoreRuntimeSlotReturn
  handleImageAnnotateAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleImageCapabilityAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleImageCustomAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleImageDialogueCanvasPick(...args: unknown[]): CoreRuntimeSlotReturn
  handleImageDownloadAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleImageEditTextAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleImageEraseAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleImageExpandAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleImageGridSplitAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleImageInpaintAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleImageInpaintCapabilityAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleImageInpaintSubmit(...args: unknown[]): CoreRuntimeSlotReturn
  handleImageMarkRecognize(...args: unknown[]): CoreRuntimeSlotReturn
  handleImageNodeDblClick(...args: unknown[]): CoreRuntimeSlotReturn
  handleImagePromptReverseAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleLogout(...args: unknown[]): CoreRuntimeSlotReturn
  handleMediaNodeContextMenu(...args: unknown[]): CoreRuntimeSlotReturn
  handleMergeStoryboardGroup(...args: unknown[]): CoreRuntimeSlotReturn
  handleMultiSelectBatchDownload(...args: unknown[]): CoreRuntimeSlotReturn
  handleMultiSelectGroup(...args: unknown[]): CoreRuntimeSlotReturn
  handleMultiSelectLayout(...args: unknown[]): CoreRuntimeSlotReturn
  handleMultiSelectSaveToAssets(...args: unknown[]): CoreRuntimeSlotReturn
  handleNodeClick(...args: unknown[]): CoreRuntimeSlotReturn
  handleNodeDataChange(...args: unknown[]): CoreRuntimeSlotReturn
  handleNodeEdgeLinked(...args: unknown[]): CoreRuntimeSlotReturn
  handleOpenVideoGenPromptBar(...args: unknown[]): CoreRuntimeSlotReturn
  handleRedo(...args: unknown[]): CoreRuntimeSlotReturn
  handleSubmitSaveSkill(...args: unknown[]): CoreRuntimeSlotReturn
  handleTextPickerAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleTidyCanvas(...args: unknown[]): CoreRuntimeSlotReturn
  handleUndo(...args: unknown[]): CoreRuntimeSlotReturn
  handleUngroup(...args: unknown[]): CoreRuntimeSlotReturn
  handleUserMenuAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleVideoCapabilityAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleVideoDownloadAction(...args: unknown[]): CoreRuntimeSlotReturn
  handleVideoGenCanvasPick(...args: unknown[]): CoreRuntimeSlotReturn
  handleVideoGenerationTaskComplete(...args: unknown[]): CoreRuntimeSlotReturn
  handleVideoNodeDblClick(...args: unknown[]): CoreRuntimeSlotReturn
  handleVideoPickerAction(...args: unknown[]): CoreRuntimeSlotReturn
  hasCanvasFileDrag(...args: unknown[]): CoreRuntimeSlotReturn
  hasImageDialogueSourceRef(...args: unknown[]): CoreRuntimeSlotReturn
  hideImageMarkHint(...args: unknown[]): CoreRuntimeSlotReturn
  inferGenerationTaskDescriptionFromNode(...args: unknown[]): CoreRuntimeSlotReturn
  isGraphNodePointerTarget(...args: unknown[]): CoreRuntimeSlotReturn
  isImageMarkAnalysisInProgress(...args: unknown[]): CoreRuntimeSlotReturn
  isImageUploadFile(...args: unknown[]): CoreRuntimeSlotReturn
  isNodeGenerating(...args: unknown[]): CoreRuntimeSlotReturn
  isVideoUploadFile(...args: unknown[]): CoreRuntimeSlotReturn
  linkImageSourceFromEdge(...args: unknown[]): CoreRuntimeSlotReturn
  listSavedCanvasSkills(...args: unknown[]): CoreRuntimeSlotReturn
  loadAssetCenterItems(...args: unknown[]): CoreRuntimeSlotReturn
  loadImageGenPromptFields(...args: unknown[]): CoreRuntimeSlotReturn
  loadPromptBarContext(...args: unknown[]): CoreRuntimeSlotReturn
  loadVideoGenPromptFields(...args: unknown[]): CoreRuntimeSlotReturn
  mapElementGroupRecord(...args: unknown[]): CoreRuntimeSlotReturn
  mapSkillToAssetCenterItem(...args: unknown[]): CoreRuntimeSlotReturn
  markCanvasContentReady(...args: unknown[]): CoreRuntimeSlotReturn
  mergePendingSaveType(...args: unknown[]): CoreRuntimeSlotReturn
  moveNodeLayer(...args: unknown[]): CoreRuntimeSlotReturn
  normalizeCutoutMode(...args: unknown[]): CoreRuntimeSlotReturn
  normalizeImageDialogueSettings(...args: unknown[]): CoreRuntimeSlotReturn
  normalizeVideoDialogueSettings(...args: unknown[]): CoreRuntimeSlotReturn
  notifyTextNodeUpdated(...args: unknown[]): CoreRuntimeSlotReturn
  onCanvasDragEnter(...args: unknown[]): CoreRuntimeSlotReturn
  onCanvasDragLeave(...args: unknown[]): CoreRuntimeSlotReturn
  onCanvasDragOver(...args: unknown[]): CoreRuntimeSlotReturn
  onCanvasFileDrop(...args: unknown[]): CoreRuntimeSlotReturn
  onCanvasGroupBlankPointerMove(...args: unknown[]): CoreRuntimeSlotReturn
  onCanvasImageContextMenuCapture(...args: unknown[]): CoreRuntimeSlotReturn
  onConnectMenuItem(...args: unknown[]): CoreRuntimeSlotReturn
  onFileSelected(...args: unknown[]): CoreRuntimeSlotReturn
  onGoHome(...args: unknown[]): CoreRuntimeSlotReturn
  onGraphDragOver(...args: unknown[]): CoreRuntimeSlotReturn
  onGraphDrop(...args: unknown[]): CoreRuntimeSlotReturn
  onGroupOverlayDragStart(...args: unknown[]): CoreRuntimeSlotReturn
  onGroupOverlayResizeStart(...args: unknown[]): CoreRuntimeSlotReturn
  onGroupOverlaySelectGroup(...args: unknown[]): CoreRuntimeSlotReturn
  onGroupOverlayTitleChange(...args: unknown[]): CoreRuntimeSlotReturn
  onImageCropComplete(...args: unknown[]): CoreRuntimeSlotReturn
  onImageDialogueUploadFiles(...args: unknown[]): CoreRuntimeSlotReturn
  onImageToolbarAction(...args: unknown[]): CoreRuntimeSlotReturn
  onLoadProjects(...args: unknown[]): CoreRuntimeSlotReturn
  onMenuItem(...args: unknown[]): CoreRuntimeSlotReturn
  onPageShow(...args: unknown[]): CoreRuntimeSlotReturn
  onPageUnload(...args: unknown[]): CoreRuntimeSlotReturn
  onPromptAddCanvasNode(...args: unknown[]): CoreRuntimeSlotReturn
  onPromptUploadFiles(...args: unknown[]): CoreRuntimeSlotReturn
  onRemoveImageGenSourceRef(...args: unknown[]): CoreRuntimeSlotReturn
  onRemoveVideoSourceRef(...args: unknown[]): CoreRuntimeSlotReturn
  onScrollerScroll(...args: unknown[]): CoreRuntimeSlotReturn
  onTextExpandInput(...args: unknown[]): CoreRuntimeSlotReturn
  onTextFormatAction(...args: unknown[]): CoreRuntimeSlotReturn
  onVideoGenAddCanvasNode(...args: unknown[]): CoreRuntimeSlotReturn
  onVideoGenQuickAction(...args: unknown[]): CoreRuntimeSlotReturn
  onVideoGenUploadFiles(...args: unknown[]): CoreRuntimeSlotReturn
  onVideoHdStart(...args: unknown[]): CoreRuntimeSlotReturn
  onVisibilityChange(...args: unknown[]): CoreRuntimeSlotReturn
  onZoomMenuAction(...args: unknown[]): CoreRuntimeSlotReturn
  openAddMenuAtGraphPoint(...args: unknown[]): CoreRuntimeSlotReturn
  openAssetCenterPanel(...args: unknown[]): CoreRuntimeSlotReturn
  openAssetsPanel(...args: unknown[]): CoreRuntimeSlotReturn
  openComboModal(...args: unknown[]): CoreRuntimeSlotReturn
  openConnectMenu(...args: unknown[]): CoreRuntimeSlotReturn
  openConnectMenuByNodeId(...args: unknown[]): CoreRuntimeSlotReturn
  openFileUploadPicker(...args: unknown[]): CoreRuntimeSlotReturn
  openImageCrop(...args: unknown[]): CoreRuntimeSlotReturn
  openImageCustom(...args: unknown[]): CoreRuntimeSlotReturn
  openImageDialogue(...args: unknown[]): CoreRuntimeSlotReturn
  openImageEditText(...args: unknown[]): CoreRuntimeSlotReturn
  openImageErase(...args: unknown[]): CoreRuntimeSlotReturn
  openImageExpand(...args: unknown[]): CoreRuntimeSlotReturn
  openImageGenPromptBar(...args: unknown[]): CoreRuntimeSlotReturn
  openImageGridSplit(...args: unknown[]): CoreRuntimeSlotReturn
  openImageInpaint(...args: unknown[]): CoreRuntimeSlotReturn
  openImagePreview(...args: unknown[]): CoreRuntimeSlotReturn
  openImageToolbarMore(...args: unknown[]): CoreRuntimeSlotReturn
  openMediaContextMenu(...args: unknown[]): CoreRuntimeSlotReturn
  openMediaPreview(...args: unknown[]): CoreRuntimeSlotReturn
  openNewProject(...args: unknown[]): CoreRuntimeSlotReturn
  openTextExpand(...args: unknown[]): CoreRuntimeSlotReturn
  openVideoDialogue(...args: unknown[]): CoreRuntimeSlotReturn
  openVideoGenPromptBar(...args: unknown[]): CoreRuntimeSlotReturn
  paintImageResizeOverlay(...args: unknown[]): CoreRuntimeSlotReturn
  parseCanvasAssetDragPayload(...args: unknown[]): CoreRuntimeSlotReturn
  parseCanvasElementGroupDragPayload(...args: unknown[]): CoreRuntimeSlotReturn
  pasteNode(...args: unknown[]): CoreRuntimeSlotReturn
  pasteNodePayload(...args: unknown[]): CoreRuntimeSlotReturn
  pauseAutoSave(...args: unknown[]): CoreRuntimeSlotReturn
  persistCanvasToServer(...args: unknown[]): CoreRuntimeSlotReturn
  persistGenerationTaskBinding(...args: unknown[]): CoreRuntimeSlotReturn
  persistImageGenPrompt(...args: unknown[]): CoreRuntimeSlotReturn
  persistPromptBarDraft(...args: unknown[]): CoreRuntimeSlotReturn
  persistTextExpandContent(...args: unknown[]): CoreRuntimeSlotReturn
  persistVideoGenPrompt(...args: unknown[]): CoreRuntimeSlotReturn
  plainTextToEditorHtml(...args: unknown[]): CoreRuntimeSlotReturn
  positionImageContextMenu(...args: unknown[]): CoreRuntimeSlotReturn
  recenterToNodes(...args: unknown[]): CoreRuntimeSlotReturn
  recordCanvasDescription(...args: unknown[]): CoreRuntimeSlotReturn
  recordGroupTaskFinishedAsset(...args: unknown[]): CoreRuntimeSlotReturn
  recordUploadCanvasDescription(...args: unknown[]): CoreRuntimeSlotReturn
  refreshPromptSourcePreviews(...args: unknown[]): CoreRuntimeSlotReturn
  removeConnectPreviewEdge(...args: unknown[]): CoreRuntimeSlotReturn
  removeHoveredEdge(...args: unknown[]): CoreRuntimeSlotReturn
  removeNodeById(...args: unknown[]): CoreRuntimeSlotReturn
  removePromptImageSource(...args: unknown[]): CoreRuntimeSlotReturn
  removeSelectedEdge(...args: unknown[]): CoreRuntimeSlotReturn
  removeSelectedElementMark(...args: unknown[]): CoreRuntimeSlotReturn
  removeSelectedNodes(...args: unknown[]): CoreRuntimeSlotReturn
  requestCanvasUpload(...args: unknown[]): CoreRuntimeSlotReturn
  resetCanvasInteractionState(...args: unknown[]): CoreRuntimeSlotReturn
  resetCanvasPanCursorState(...args: unknown[]): CoreRuntimeSlotReturn
  resetGroupBlankHoverCursor(...args: unknown[]): CoreRuntimeSlotReturn
  resetImageCrop(...args: unknown[]): CoreRuntimeSlotReturn
  resetImageDialogue(...args: unknown[]): CoreRuntimeSlotReturn
  resetImageDialogueInputOnSourceNode(...args: unknown[]): CoreRuntimeSlotReturn
  resetImageEditText(...args: unknown[]): CoreRuntimeSlotReturn
  resetImageExpand(...args: unknown[]): CoreRuntimeSlotReturn
  resetImageGridSplit(...args: unknown[]): CoreRuntimeSlotReturn
  resetImageToolbarMore(...args: unknown[]): CoreRuntimeSlotReturn
  resetSourceImageDialogueAfterSuccess(...args: unknown[]): CoreRuntimeSlotReturn
  resetVideoDialogue(...args: unknown[]): CoreRuntimeSlotReturn
  resetVideoFramesPanel(...args: unknown[]): CoreRuntimeSlotReturn
  resetVideoHdPanel(...args: unknown[]): CoreRuntimeSlotReturn
  resolveActiveProjectId(...args: unknown[]): CoreRuntimeSlotReturn
  resolveGenerationResultFileName(...args: unknown[]): CoreRuntimeSlotReturn
  resolveGroupDragPreviewNode(...args: unknown[]): CoreRuntimeSlotReturn
  resolveImageGenTextSourcePreview(...args: unknown[]): CoreRuntimeSlotReturn
  resolveLibraryAssetBindId(...args: unknown[]): CoreRuntimeSlotReturn
  resolveMarkableImageNodeIds(...args: unknown[]): CoreRuntimeSlotReturn
  resolveOverlayGroup(...args: unknown[]): CoreRuntimeSlotReturn
  resolvePromptReferenceAssetIds(...args: unknown[]): CoreRuntimeSlotReturn
  resolveVideoResultLayoutSize(...args: unknown[]): CoreRuntimeSlotReturn
  resolveVideoUpstreamPrompt(...args: unknown[]): CoreRuntimeSlotReturn
  restoreCanvasPickTargetSelection(...args: unknown[]): CoreRuntimeSlotReturn
  resumeCanvasGenerationTasks(...args: unknown[]): CoreRuntimeSlotReturn
  returnFromElementSelect(...args: unknown[]): CoreRuntimeSlotReturn
  revealVideoDialogueAfterGenerationFailure(...args: unknown[]): CoreRuntimeSlotReturn
  runBatchDownloadForNodeIds(...args: unknown[]): CoreRuntimeSlotReturn
  runGroupAiGenerationPipeline(...args: unknown[]): CoreRuntimeSlotReturn
  runImagePromptReverseTask(...args: unknown[]): CoreRuntimeSlotReturn
  runImageTo3DTask(...args: unknown[]): CoreRuntimeSlotReturn
  runRemoteCanvasSaveJob(...args: unknown[]): CoreRuntimeSlotReturn
  sanitizePastedNodeData(...args: unknown[]): CoreRuntimeSlotReturn
  scheduleUpdateNodeToolbar(...args: unknown[]): CoreRuntimeSlotReturn
  scheduleViewportNodeVisibilitySync(...args: unknown[]): CoreRuntimeSlotReturn
  seedPromptImageRefs(...args: unknown[]): CoreRuntimeSlotReturn
  selectElementMark(...args: unknown[]): CoreRuntimeSlotReturn
  selectGraphNodes(...args: unknown[]): CoreRuntimeSlotReturn
  selectProject(...args: unknown[]): CoreRuntimeSlotReturn
  selectSingleGraphNode(...args: unknown[]): CoreRuntimeSlotReturn
  setConnectSourceNodeMetaHidden(...args: unknown[]): CoreRuntimeSlotReturn
  setRubberbandEnabled(...args: unknown[]): CoreRuntimeSlotReturn
  setTextEditorToolbarActive(...args: unknown[]): CoreRuntimeSlotReturn
  setupMinimap(...args: unknown[]): CoreRuntimeSlotReturn
  shouldHideImageDimensionOverlay(...args: unknown[]): CoreRuntimeSlotReturn
  showImageMarkHint(...args: unknown[]): CoreRuntimeSlotReturn
  spawnMediaFilesAtPoint(...args: unknown[]): CoreRuntimeSlotReturn
  stopAutoSave(...args: unknown[]): CoreRuntimeSlotReturn
  stopGroupOverlayDrag(...args: unknown[]): CoreRuntimeSlotReturn
  submitTextPrompt(...args: unknown[]): CoreRuntimeSlotReturn
  syncConnectPreviewEdgeTarget(...args: unknown[]): CoreRuntimeSlotReturn
  syncEdgeHighlight(...args: unknown[]): CoreRuntimeSlotReturn
  syncGroupAiProvenance(...args: unknown[]): CoreRuntimeSlotReturn
  syncGroupBlankHoverCursor(...args: unknown[]): CoreRuntimeSlotReturn
  syncGroupedNodeMove(...args: unknown[]): CoreRuntimeSlotReturn
  syncHistoryState(...args: unknown[]): CoreRuntimeSlotReturn
  syncImageDialogueSourceRefs(...args: unknown[]): CoreRuntimeSlotReturn
  syncImageElementMarkSelection(...args: unknown[]): CoreRuntimeSlotReturn
  syncImageMarkTargets(...args: unknown[]): CoreRuntimeSlotReturn
  syncNodeCount(...args: unknown[]): CoreRuntimeSlotReturn
  syncNodeSelectionHighlight(...args: unknown[]): CoreRuntimeSlotReturn
  syncPendingRemoteSaveTypeFlag(...args: unknown[]): CoreRuntimeSlotReturn
  syncSelectionFromGraph(...args: unknown[]): CoreRuntimeSlotReturn
  syncVideoNodeAspectRatio(...args: unknown[]): CoreRuntimeSlotReturn
  syncVideoSourceRefsSnapshot(...args: unknown[]): CoreRuntimeSlotReturn
  syncViewportNodeVisibility(...args: unknown[]): CoreRuntimeSlotReturn
  syncZoom(...args: unknown[]): CoreRuntimeSlotReturn
  teardownMinimap(...args: unknown[]): CoreRuntimeSlotReturn
  toggleAddMenu(...args: unknown[]): CoreRuntimeSlotReturn
  toggleAssetCenterPanel(...args: unknown[]): CoreRuntimeSlotReturn
  toggleAssetsPanel(...args: unknown[]): CoreRuntimeSlotReturn
  toggleCanvasBgTheme(...args: unknown[]): CoreRuntimeSlotReturn
  toggleGrid(...args: unknown[]): CoreRuntimeSlotReturn
  toggleHistoryPanel(...args: unknown[]): CoreRuntimeSlotReturn
  toggleImageAddToDialogMenu(...args: unknown[]): CoreRuntimeSlotReturn
  toggleImageDialogue(...args: unknown[]): CoreRuntimeSlotReturn
  toggleImageDialogueCanvasPickMode(...args: unknown[]): CoreRuntimeSlotReturn
  toggleImageHdMenu(...args: unknown[]): CoreRuntimeSlotReturn
  toggleImageNodeLock(...args: unknown[]): CoreRuntimeSlotReturn
  toggleImageToolbarMoreMenu(...args: unknown[]): CoreRuntimeSlotReturn
  toggleMinimap(...args: unknown[]): CoreRuntimeSlotReturn
  togglePanMode(...args: unknown[]): CoreRuntimeSlotReturn
  toggleProjectMenu(...args: unknown[]): CoreRuntimeSlotReturn
  toggleShortcutsPanel(...args: unknown[]): CoreRuntimeSlotReturn
  toggleUserMenu(...args: unknown[]): CoreRuntimeSlotReturn
  toggleVideoDialogue(...args: unknown[]): CoreRuntimeSlotReturn
  toggleVideoFramesPanel(...args: unknown[]): CoreRuntimeSlotReturn
  toggleVideoGenCanvasPickMode(...args: unknown[]): CoreRuntimeSlotReturn
  toggleVideoHdPanel(...args: unknown[]): CoreRuntimeSlotReturn
  toggleZoomMenu(...args: unknown[]): CoreRuntimeSlotReturn
  triggerCanvasUploadShortcut(...args: unknown[]): CoreRuntimeSlotReturn
  triggerFileInputClick(...args: unknown[]): CoreRuntimeSlotReturn
  unbindGraphDropListeners(...args: unknown[]): CoreRuntimeSlotReturn
  unbindKeyboard(...args: unknown[]): CoreRuntimeSlotReturn
  unbindLongPressPan(...args: unknown[]): CoreRuntimeSlotReturn
  unbindScrollerScrollListener(...args: unknown[]): CoreRuntimeSlotReturn
  updateAddMenuPosition(...args: unknown[]): CoreRuntimeSlotReturn
  updateChatTaskNodeTitleFromPayload(...args: unknown[]): CoreRuntimeSlotReturn
  updateConnectMenuPosition(...args: unknown[]): CoreRuntimeSlotReturn
  updateEdgeDeleteButtonPosition(...args: unknown[]): CoreRuntimeSlotReturn
  updateGroupToolbarPosition(...args: unknown[]): CoreRuntimeSlotReturn
  updateImageGenPromptBarPosition(...args: unknown[]): CoreRuntimeSlotReturn
  updateImageMarkHintPositions(...args: unknown[]): CoreRuntimeSlotReturn
  updateImageResizeOverlay(...args: unknown[]): CoreRuntimeSlotReturn
  updateMultiSelectToolbarPosition(...args: unknown[]): CoreRuntimeSlotReturn
  updatePromptBarPosition(...args: unknown[]): CoreRuntimeSlotReturn
  updateTextFormatToolbarPosition(...args: unknown[]): CoreRuntimeSlotReturn
  updateVideoGenPromptBarPosition(...args: unknown[]): CoreRuntimeSlotReturn
  uploadFileToCanvasNode(...args: unknown[]): CoreRuntimeSlotReturn
  uploadGridSplitImagesInBackground(...args: unknown[]): CoreRuntimeSlotReturn
  upsertCanvasProject(...args: unknown[]): CoreRuntimeSlotReturn
  waitForNodeUploadDone(...args: unknown[]): CoreRuntimeSlotReturn
  zoomFitToScreen(...args: unknown[]): CoreRuntimeSlotReturn
  zoomIn(...args: unknown[]): CoreRuntimeSlotReturn
  zoomOut(...args: unknown[]): CoreRuntimeSlotReturn
  zoomToScale(...args: unknown[]): CoreRuntimeSlotReturn
}

