/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Canvas: typeof import('./components/Canvas/index.vue')['default']
    CanvasAddMenu: typeof import('./components/Canvas/panels/CanvasAddMenu.vue')['default']
    CanvasAssetsPanel: typeof import('./components/Canvas/panels/CanvasAssetsPanel.vue')['default']
    CanvasBottomControls: typeof import('./components/Canvas/panels/CanvasBottomControls.vue')['default']
    CanvasBottomDock: typeof import('./components/Canvas/panels/CanvasBottomDock.vue')['default']
    CanvasConnectMenu: typeof import('./components/Canvas/panels/CanvasConnectMenu.vue')['default']
    CanvasElementSelectBar: typeof import('./components/Canvas/panels/CanvasElementSelectBar.vue')['default']
    CanvasGroupOverlay: typeof import('./components/Canvas/panels/CanvasGroupOverlay.vue')['default']
    CanvasGroupToolbar: typeof import('./components/Canvas/panels/CanvasGroupToolbar.vue')['default']
    CanvasHeader: typeof import('./components/Canvas/panels/CanvasHeader.vue')['default']
    CanvasHistoryPanel: typeof import('./components/Canvas/CanvasHistoryPanel.vue')['default']
    CanvasImagePreview: typeof import('./components/Canvas/panels/CanvasImagePreview.vue')['default']
    CanvasLeftToolbar: typeof import('./components/Canvas/panels/CanvasLeftToolbar.vue')['default']
    CanvasMultiSelectToolbar: typeof import('./components/Canvas/panels/CanvasMultiSelectToolbar.vue')['default']
    CanvasNodeOverlays: typeof import('./components/Canvas/panels/CanvasNodeOverlays.vue')['default']
    CanvasNodeToolbar: typeof import('./components/Canvas/panels/CanvasNodeToolbar.vue')['default']
    CanvasShortcutsPanel: typeof import('./components/Canvas/CanvasShortcutsPanel.vue')['default']
    Combo: typeof import('./components/Combo/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ImageColorPickerPanel: typeof import('./components/Canvas/ImageColorPickerPanel.vue')['default']
    ImageCropOverlay: typeof import('./components/Canvas/ImageCropOverlay.vue')['default']
    ImageDialoguePanel: typeof import('./components/Canvas/ImageDialoguePanel.vue')['default']
    ImageGenNode: typeof import('./components/Canvas/nodes/ImageGenNode.vue')['default']
    ImageGenPromptPanel: typeof import('./components/Canvas/ImageGenPromptPanel.vue')['default']
    ImageGenSettingsPopover: typeof import('./components/Canvas/ImageGenSettingsPopover.vue')['default']
    ImageNode: typeof import('./components/Canvas/nodes/ImageNode.vue')['default']
    ImageStylePanel: typeof import('./components/Canvas/ImageStylePanel.vue')['default']
    Login: typeof import('./components/Login/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextFormatToolbar: typeof import('./components/Canvas/TextFormatToolbar.vue')['default']
    TextNode: typeof import('./components/Canvas/nodes/TextNode.vue')['default']
    VideoDialoguePanel: typeof import('./components/Canvas/VideoDialoguePanel.vue')['default']
    VideoFramesPanel: typeof import('./components/Canvas/VideoFramesPanel.vue')['default']
    VideoGenModelPicker: typeof import('./components/Canvas/VideoGenModelPicker.vue')['default']
    VideoGenPromptPanel: typeof import('./components/Canvas/VideoGenPromptPanel.vue')['default']
    VideoGenSettingsPopover: typeof import('./components/Canvas/VideoGenSettingsPopover.vue')['default']
    VideoHdPanel: typeof import('./components/Canvas/VideoHdPanel.vue')['default']
    VideoNode: typeof import('./components/Canvas/nodes/VideoNode.vue')['default']
    VideoStoryboardPanel: typeof import('./components/Canvas/VideoStoryboardPanel.vue')['default']
  }
}
